# This sets the global defaults, you can override the default via environment variable or CLI argument.
#
[homeseer]
url = http://127.0.0.1
refs = 1
ignorenames=CentralScene,System Notification,Power Management Notification,HeatAlarmNotification
user=admin
pass=[WHILE YOU CAN PUT CLEARTEXT PASSWORD HERE, BETTER TO USE .NETRC FILE INSTEAD]

[iotplotter]
api_key = [REPLACE WITH YOUR KEY]
#feed_id = [REPLACE WITH SELECTED FEED]
last_change_max_hours = 24
prefix = location

[grafana]
url = http://127.0.0.1:8086/
token = [REPLACE WITH YOUR TOKEN]
org = [REPLACE WITH YOUR ORG]
bucket = HomeSeer
last_change_max_hours = 50
#timeout=66

#[scaling]
## Multiply the value of Ref 123 by 0.001 (e.g., Watts to kW)
#123 = 0.001
## Multiply Ref 456 by 100 (e.g., Decimal to Percentage)
#456 = 100
###EOF###
